export const FETCH_USER = 'FETCH_USER';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEY_DETAILS = 'FETCH_SURVEY_DETAILS';
export const FETCH_CONTACT_US_DATA = 'FETCH_CONTACT_US_DATA';

